name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Reboot
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-keyscan "139.59.191.97" >> ~/.ssh/known_hosts
          ssh root@139.59.191.97 echo "hello world" > github.test
          # cd /usr/leaderboard-v3
          # git checkout master && git pull
          # pm2 restart bvgs_leaderboard
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock  
